# Generated by Django 2.2.28 on 2023-01-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cr_t', models.DateTimeField(auto_now_add=True)),
                ('mode', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('m_med', models.TextField(blank=True, null=True)),
                ('quant', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('main_c', models.CharField(blank=True, max_length=255, null=True)),
                ('fabr', models.CharField(blank=True, max_length=255, null=True)),
                ('presc_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugsOnAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.PositiveIntegerField()),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Alarm')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Drug')),
            ],
        ),
    ]
